### ISSUE TITLE
[8] Freeze when selecting song (0.2-c)

### ISSUE THREAD

**Issue by thepercentageguy** [aflacc/ProjectFNF#61] opened 2021-06-08 14:21 UTC
ProjectFNF version: 0.2-c
Type of issue: Crash/Freeze
Severity: 8
Description: Whenever i try to build & run the game (just freshly downloaded with no changes to the code) and i try to select a song the game freezes, and in debug mode it says it can't find the song IDs
Repository: None

![image](https://user-images.githubusercontent.com/54141759/121202206-67045c80-c875-11eb-91ab-883c46cdcdc0.png)

I don't know the source code all that well so i wouldn't know how to fix it myself

**Comment by aflacc** [comment] 2021-06-08 16:06
Are you compiling in html5 because mp3s are the way html5 compiles. Try compiling with windows or mac or whatever OS you have.

**Comment by thepercentageguy** [comment] 2021-06-08 16:14
> Are you compiling in html5 because mp3s are the way html5 compiles. Try compiling with windows or mac or whatever OS you have.

i'll try that thanks

**Comment by aflacc** [comment] 2021-06-08 17:02
Not sure if thats the cause just I'm suggesting that you try compiling it as a executable instead of a browser.

**Comment by aflacc** [comment] 2021-06-08 17:02
Browser compiles are really only good for debugging

**Comment by thepercentageguy** [comment] 2021-06-08 17:17
compiling to executable worked, thanks

**Comment by aflacc** [comment] 2021-06-08 17:21
Wait before you go, check the songs folder located from the root/assets/songs. look for the songs that were listed in the screenshot you sent check if theres .mp3's for them

**Comment by thepercentageguy** [comment] 2021-06-08 17:24
> Wait before you go, check the songs folder located from the root/assets/songs. look for the songs that were listed in the screenshot you sent check if theres .mp3's for them

all of them have mp3's

**Comment by aflacc** [comment] 2021-06-08 18:11
Check the export folder.
(root/export/) and find the html5 one
look in `assets/songs` and check if the mp3s are there

**Comment by thepercentageguy** [comment] 2021-06-10 15:52
> Check the export folder.
> (root/export/) and find the html5 one
> look in `assets/songs` and check if the mp3s are there

They are, sorry for the late reply lol

**Comment by aflacc** [comment] 2021-06-10 16:01
Does this issue still happen

**Comment by aflacc** [comment] 2021-06-11 17:05
Hello? is this a thing still in html5?

**Comment by ZachToonz** [comment] 2021-06-11 20:55
> Hello? is this a thing still in html5?
im guessing it is not but forgot to close it lol

**Comment by thepercentageguy** [comment] 2021-06-11 21:02
Oop sorry haven't been online I'll check tomorrow

**Comment by aflacc** [comment] 2021-06-14 15:57
did he check

**Comment by thepercentageguy** [comment] 2021-06-17 17:13
shit
i'll check rn

**Comment by thepercentageguy** [comment] 2021-06-17 17:57
it is

**Comment by MagnusStrom** [comment] 2021-06-18 02:24
I'll be closing this because it's on an old version. try on the newest version

**Closed by MagnusStrom** 2021-06-18 02:24 UTC
Labels: HTML5, bug

**Comment by thepercentageguy** [comment] 2021-06-18 11:44
I did
