### ISSUE TITLE
Near-death icon issue

### ISSUE THREAD

**Issue by george2781** [aflacc/ProjectFNF#16] opened 2021-04-27 16:50 UTC
A bit of a minor issue but compiling the game (unmodified) and almost dying in a stage will lead to both characters (bf and the opponent) having a near-death character icon as seen below
![Screenshot (3)](https://user-images.githubusercontent.com/42376099/116280727-e421b980-a780-11eb-9d1b-8b7128971d88.png)

(Windows compile, no modification to source code whatsoever)

**Comment by george2781** [comment] 2021-04-27 16:57
A similar effect is visible in week 4, but instead of losing, it happens when you are winning
![Screenshot (7)](https://user-images.githubusercontent.com/42376099/116281888-0ff16f00-a782-11eb-839e-87fbb49eddff.png)

**Comment by aflacc** [comment] 2021-04-27 17:36
The values of their health icon might only have 2. If you have access to the code, add the first value as a third value

**Comment by aflacc** [comment] 2021-04-27 17:37
Technically a dupe of #11

**Comment by aflacc** [comment] 2021-04-27 17:40
Fixed,

**Closed by aflacc** 2021-04-27 17:40 UTC
Labels: bug, duplicate
